--CREATE USER simple IDENTIFIED BY password2Change;
-- GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW,
-- 	CREATE PROCEDURE,CREATE SYNONYM, CREATE SEQUENCE, CREATE TRIGGER TO simple;
CREATE TABLE TEXT_KEY_TABLE (
	TEXT_KEY VARCHAR2(510) NOT NULL
);

CREATE UNIQUE INDEX TEXT_KEY_TABLE_UK1 ON TEXT_KEY_TABLE (TEXT_KEY);

ALTER TABLE TEXT_KEY_TABLE ADD CONSTRAINT TEXT_KEY_TABLE_PK PRIMARY KEY (TEXT_KEY) ENABLE;
CREATE TABLE SIMPLE_TABLE (
	ID NUMBER(9) NOT NULL,
	LABEL VARCHAR2(510) NOT NULL,
	DESCRIPTION VARCHAR2(510)
);

CREATE SEQUENCE SIMPLE_TABLE_SEQ MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 2 NOCACHE NOORDER NOCYCLE;

CREATE OR REPLACE TRIGGER SIMPLE_TABLE_TRIG
BEFORE INSERT ON SIMPLE_TABLE
FOR EACH ROW BEGIN
	IF :NEW.ID IS NULL THEN
		SELECT SIMPLE_TABLE_SEQ.nextVal
		INTO :NEW.ID
		FROM dual;
	END IF;
END;
/
ALTER TRIGGER SIMPLE_TABLE_TRIG ENABLE;
CREATE UNIQUE INDEX SIMPLE_TABLE_UK1 ON SIMPLE_TABLE (ID);

ALTER TABLE SIMPLE_TABLE ADD CONSTRAINT SIMPLE_TABLE_PK PRIMARY KEY (ID) ENABLE;
CREATE TABLE SIMPLE_VALUE_TABLE (
	ID NUMBER(9) NOT NULL,
	MEMO CLOB,
	DATE_TIME TIMESTAMP,
	CURRENCY NUMBER(8,2),
	YES_NO VARCHAR2(1),
	LABEL_LOOKUP NUMBER(9),
	NUMBER_ NUMBER(5),
	PRECISION_NUMBER NUMBER(8,4),
	FOREIGN_KEY NUMBER(9),
	TEXT_LOOKUP VARCHAR2(510)
);

CREATE SEQUENCE SIMPLE_VALUE_TABLE_SEQ MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 2 NOCACHE NOORDER NOCYCLE;

CREATE OR REPLACE TRIGGER SIMPLE_VALUE_TABLE_TRIG
BEFORE INSERT ON SIMPLE_VALUE_TABLE
FOR EACH ROW BEGIN
	IF :NEW.ID IS NULL THEN
		SELECT SIMPLE_VALUE_TABLE_SEQ.nextVal
		INTO :NEW.ID
		FROM dual;
	END IF;
END;
/
ALTER TRIGGER SIMPLE_VALUE_TABLE_TRIG ENABLE;
CREATE UNIQUE INDEX SIMPLE_VALUE_TABLE_UK1 ON SIMPLE_VALUE_TABLE (ID);

ALTER TABLE SIMPLE_VALUE_TABLE ADD CONSTRAINT SIMPLE_VALUE_TABLE_PK PRIMARY KEY (ID) ENABLE;

ALTER TABLE SIMPLE_VALUE_TABLE ADD CONSTRAINT SIMPLE_VALUE_TABLE_FK1 FOREIGN KEY (LABEL_LOOKUP)
	REFERENCES SIMPLE_TABLE (ID) ENABLE;

ALTER TABLE SIMPLE_VALUE_TABLE ADD CONSTRAINT SIMPLE_VALUE_TABLE_FK2 FOREIGN KEY (FOREIGN_KEY)
	REFERENCES SIMPLE_TABLE (ID) ENABLE;

ALTER TABLE SIMPLE_VALUE_TABLE ADD CONSTRAINT SIMPLE_VALUE_TABLE_FK3 FOREIGN KEY (TEXT_LOOKUP)
	REFERENCES TEXT_KEY_TABLE (TEXT_KEY) ENABLE;
