DROP SEQUENCE SIMPLE_TABLE_SEQ;
DROP SEQUENCE SIMPLE_VALUE_TABLE_SEQ;
DROP TRIGGER SIMPLE_TABLE_TRIG;
DROP TRIGGER SIMPLE_VALUE_TABLE_TRIG;
DROP TABLE SIMPLE_VALUE_TABLE;
DROP TABLE TEXT_KEY_TABLE;
DROP TABLE SIMPLE_TABLE;