INSERT INTO SIMPLE_TABLE(ID, LABEL, DESCRIPTION) VALUES (1, 'label1', 'description1');
INSERT INTO SIMPLE_VALUE_TABLE(ID, DATE_TIME, CURRENCY, YES_NO, LABEL_LOOKUP, NUMBERX, PRECISION_NUMBER, FOREIGN_KEY, TEXT_LOOKUP) VALUES (1, TO_TIMESTAMP('04/01/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 3.5000, 'Y', 1, 2, 1.1, 1, 'text1');
DECLARE
str varchar2(32767);
BEGIN
	str := 'test memo';
UPDATE SIMPLE_VALUE_TABLE SET MEMO = str WHERE ID = 1;
END;
/
INSERT INTO TEXT_KEY_TABLE(TEXT_KEY) VALUES ('text1');

